# Generated by Django 2.1.2 on 2018-12-05 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('image', models.ImageField(default='products/none/no_image.png', upload_to='products/')),
                ('categoria', models.CharField(choices=[('0', 'Mac'), ('1', 'iPhone'), ('2', 'iPad'), ('3', 'Watch'), ('4', 'Audio'), ('5', 'Accesorios')], max_length=40, verbose_name='Categoría')),
                ('novedad', models.BooleanField(default=False, verbose_name='¿Producto Nuevo?')),
                ('precio_normal', models.IntegerField(verbose_name='Precio Normal')),
                ('oferta', models.BooleanField(default=False, verbose_name='¿Producto en oferta?')),
                ('precio_oferta', models.IntegerField(verbose_name='Precio Oferta')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Tienda')),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Producto')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Store')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Store'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tienda_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Store'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
