# Generated by Django 2.1.2 on 2018-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_employee_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='administrador',
        ),
        migrations.AddField(
            model_name='employee',
            name='encargado',
            field=models.BooleanField(default=False, verbose_name='Encargado de Tienda'),
        ),
    ]
