# Generated by Django 2.1.2 on 2018-12-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_store_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
