# Generated by Django 2.1.2 on 2018-12-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_venta_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='encargado',
        ),
    ]
