# Generated by Django 2.1.2 on 2018-12-06 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_remove_employee_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vendedor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
