# Generated by Django 2.1.2 on 2018-12-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_store_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='vendedor',
        ),
    ]
